export const SCREEN_COURSES = 'coursesScreen';
export const SCREEN_COURSE_CATEGORY = 'courseCategoryScreen';
export const SCREEN_MATERIAL_STORE = 'materialStore';
export const SCREEN_PRODUCT_DETAIL = 'productDetail';
export const SCREEN_TEST_SERIES_FOLDER = 'testSeriesFolder';
export const SCREEN_TEST_SERIES_RESULT = 'testSeriesResult';

export const API_BASE_URL = 'https://chahalacademy.com/api/';

export const CURRENT_AFFAIR_CATEGORY_TYPE = {
  IMPORTANT_CURRENT_AFFAIR: 'important-current-affairs',
  READ_INDIAN_EXPRESS: 'read-indian-express',
  CURRENT_AFFAIR: 'current-affairs',
  INDIAN_EXPRESS: 'indian-express',
  ANSWER_WRITING: 'answer-writing',
  CURRENT_AFFAIR_QUIZE: 'daily-current-affairs-quiz',
  CURRENT_AFFAIR_MAGAZINE: 'current-affairs-magazine',
  YOJANA_MAGAZINE: 'yojana-magazine',
  KURUKSHETRA_MAGAZINE: 'kurukshetra-magazine',
};

// ANIMATION
export const ANIMATION_TYPES = {
  BOUNCE: 'bounce',
  FLASH: 'flash',
  JELLO: 'jello',
  PULSE: 'pulse',
  ROTATE: 'rotate',
  RUBBER_BAND: 'rubberBand',
  SHAKE: 'shake',
  SWING: 'swing',
  TADA: 'tada',
  WOBBLE: 'wobble',
  BOUNCE_IN: 'bounceIn',
  BOUNCE_IN_DOWN: 'bounceInDown',
  BOUNCE_IN_UP: 'bounceInUp',
  BOUNCE_IN_LEFT: 'bounceInLeft',
  BOUNCE_IN_RIGHT: 'bounceInRight',
  BOUNCE_OUT: 'bounceOut',
  BOUNCE_OUT_DOWN: 'bounceOutDown',
  BOUNCE_OUT_UP: 'bounceOutUp',
  BOUNCE_OUT_LEFT: 'bounceOutLeft',
  BOUNCE_OUT_RIGHT: 'bounceOutRight',
  FADE_IN: 'fadeIn',
  FADE_IN_DOWN: 'fadeInDown',
  FADE_IN_DOWN_BIG: 'fadeInDownBig',
  FADE_IN_UP: 'fadeInUp',
  FADE_IN_UP_BIG: 'fadeInUpBig',
  FADE_IN_LEFT: 'fadeInLeft',
  FADE_IN_LEFT_BIG: 'fadeInLeftBig',
  FADE_IN_RIGHT: 'fadeInRight',
  FADE_IN_RIGHT_BIG: 'fadeInRightBig',
  FADE_OUT: 'fadeOut',
  FADE_OUT_DOWN: 'fadeOutDown',
  FADE_OUT_DOWN_BIG: 'fadeOutDownBig',
  FADE_OUT_UP: 'fadeOutUp',
  FADE_OUT_UP_BIG: 'fadeOutUpBig',
  FADE_OUT_LEFT: 'fadeOutLeft',
  FADE_OUT_LEFT_BIG: 'fadeOutLeftBig',
  FADE_OUT_RIGHT: 'fadeOutRight',
  FADE_OUT_RIGHT_BIG: 'fadeOutRightBig',
  FLIP_IN_X: 'flipInX',
  FLIP_IN_Y: 'flipInY',
  FLIP_OUT_X: 'flipOutX',
  FLIP_OUT_X: 'flipOutY',
  LIGHT_SPEED_IN: 'lightSpeedIn',
  LIGHT_SPEED_OUT: 'lightSpeedOut',
  SLIDE_IN_DOWN: 'slideInDown',
  SLIDE_IN_UP: 'slideInUp',
  SLIDE_IN_LEFTT: 'slideInLeft',
  SLIDE_IN_RIGHT: 'slideInRight',
  SLIDE_OUT_DOWN: 'slideOutDown',
  SLIDE_OUT_UP: 'slideOutUp',
  SLIDE_OUT_LEFT: 'slideOutLeft',
  SLIDE_OUT_RIGHT: 'slideOutRight',
  ZOOM_IN: 'zoomIn',
  ZOOM_IN_DOWN: 'zoomInDown',
  ZOOM_IN_UP: 'zoomInUp',
  ZOOM_IN_LEFT: 'zoomInLeft',
  ZOOM_IN_RIGHT: 'zoomInRight',
  ZOOM_OUT: 'zoomOut',
  ZOOM_OUT_DOWN: 'zoomOutDown',
  ZOOM_OUT_UP: 'zoomOutUp',
  ZOOM_OUT_LEFT: 'zoomOutLeft',
  ZOOM_OUT_RIGHT: 'zoomOutRight',
};

export const EASING_TYPE = {
  LINEAR: 'linear',
  EASE: 'ease',
  EASE_IN: 'ease-in',
  EASE_OUT: 'ease-out',
  EASE_IN_OUT: 'ease-in-out',
  EASE_IN_CUBIC: 'ease-in-cubic',
  EASE_OUT_CUBIC: 'ease-out-cubic',
  EASE_IN_OUT_CUBIC: 'ease-in-out-cubic',
  EASE_IN_CIRC: 'ease-in-circ',
  EASE_OUT_CIRC: 'ease-out-circ',
  EASE_IN_OUT_CIRC: 'ease-in-out-circ',
  EASE_IN_EXPO: 'ease-in-expo',
  EASE_OUT_EXPO: 'ease-out-expo',
  EASE_IN_OUT_EXPO: 'ease-in-out-expo',
  EASE_IN_QUAD: 'ease-in-quad',
  EASE_OUT_QUAD: 'ease-out-quad',
  EASE_IN_OUT_QUAD: 'ease-in-out-quad',
  EASE_IN_QART: 'ease-in-quart',
  EASE_OUT_QUART: 'ease-out-quart',
  EASE_IN_OUT_QUART: 'ease-in-out-quart',
  EASE_IN_QUINT: 'ease-in-quint',
  EASE_OUT_QUINT: 'ease-out-quint',
  EASE_IN_OUT_QUINT: 'ease-in-out-quint',
  EASE_IN_SINE: 'ease-in-sine',
  EASE_OUT_SINE: 'ease-out-sine',
  EASE_IN_OUT_SINE: 'ease-in-out-sine',
  EASE_IN_BACK: 'ease-in-back',
  EASE_OUT_BACK: 'ease-out-back',
  EASE_IN_OUT_BACK: 'ease-in-out-back',
};
